version: "3.7"

x-defaults: &defaults
  environment:
    - MONGO_INITDB_DATABASE=mongodb
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass
    - DB_HOST=db
    - DB_PORT=27017

services:
  app:
    <<: *defaults
    build:
      context: ./app
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    <<: *defaults
    image: mongo:latest
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
    

volumes:
  mongodbdata: {}
