name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            rm -rf ~/spiny-challenge || true
            mkdir ~/spiny-challenge
            git clone https://github.com/mtomilov/spiny-challenge.git
            cd ~/spiny-challenge
            docker-compose down
            docker-compose up -d
            echo 'Successfully deployed to digital ocean'
