name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@c732d38392bd59adadcb5e688fb1f7f1d29c6951
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          usename: ${{secrets.SSH_USERNAME}}
          script: whoami
