name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            mkdir ~/spiny || true
            cd ~/spiny
            git clone git@github.com:mtomilov/spiny-challenge.git
            docker-compose up -d
            echo 'Successfully deployed to digital ocean'
